---
- name: deploy nginx local ingress controllers
  kubernetes.core.helm:
    name: "{{ ingress_name }}"
    chart_ref: ingress-nginx
    chart_repo_url: "{{ k8s_nginx_chart_url }}"
    chart_version: "{{ k8s_nginx_chart_release }}"
    release_namespace: "{{ ingress_namespace }}"
    state: "{{ item.value.state }}"
    wait: true
    wait_timeout: "{{ k8s_nginx_wait_timeout }}"
    update_repo_cache: yes
    create_namespace: yes
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    binary_path: "{{ k8s_helm_bin | default(omit) }}"
    values:
      controller:
        ingressClassResource:
          name: "{{ ingress_class }}"
          controllerValue: "k8s.io/{{ ingress_name }}"
        service:
          annotations:
            metallb.universe.tf/address-pool: "{{ item.key }}"
  vars:
    ingress_class: "nginx-{{ item.key }}"
    ingress_name: "{{ item.key }}"
    ingress_namespace: "{{ ingress_class }}"
  loop_control:
    label: "{{ item.key }}"
  loop: "{{ k8s_address_pools[k8s_cluster_type] | dict2items }}"
