---
- name: print debug information
  ansible.builtin.debug:
    msg: "using kubeconfig at '{{ k8s_kubeconfig }}'"

- name: include precondition checks
  include_tasks: "deploy/check.yml"

- name: include secret management tasks
  include_tasks: "deploy/secrets.yml"

- name: include metallb deployment tasks
  include_tasks: "deploy/metallb.yml"

- name: include certmanager deployment tasks
  include_tasks: "deploy/certmanager.yml"

- name: include ingress deployment tasks
  include_tasks: "deploy/nginx/{{ k8s_cluster_type }}.yml"

- name: include longhorn deployment tasks
  include_tasks: "deploy/longhorn.yml"
  when: k8s_longhorn_deploy | bool

- name: include olm deployment tasks
  include_tasks: "deploy/olm.yml"

- name: include argocd deployment tasks
  include_tasks: "deploy/argocd.yml"
  when: k8s_argocd_deploy | bool

- name: include strimzi deployment tasks
  include_tasks: "deploy/strimzi.yml"
  when: k8s_strimzi_deploy | bool

- name: include pgo deployment tasks
  include_tasks: "deploy/pgo.yml"
  when: k8s_pgo_deploy | bool

- name: include awx operator deployment tasks
  include_tasks: "deploy/awx-operator.yml"
  when: k8s_awxoperator_deploy | bool
