---
- name: print debug information
  ansible.builtin.debug:
    msg: "using kubeconfig at '{{ k8s_kubeconfig }}'"

- name: include verifier requirement tasks
  include_tasks: verify/requirements.yml

- name: create temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: kind
  register: _tmpdir
  when: k8s_verifier_path is not defined

- name: set verification directory default
  ansible.builtin.set_fact:
    k8s_verifier_path: "{{ _tmpdir.path }}"
  when: _tmpdir is not skipped

- block:

    - name: include secret checks
      include_tasks: verify/secrets.yml

    - name: include helm checks
      include_tasks: verify/helm.yml

    - name: include pod checks
      include_tasks: verify/pods.yml

    - name: include cert checks
      include_tasks: verify/certs.yml

    - name: include service checks
      include_tasks: verify/service.yml

    - name: include ingress checks
      include_tasks: verify/ingress.yml

    - name: include argocd checks
      ansible.builtin.include_tasks: verify/argocd.yml

    - name: include volume checks
      ansible.builtin.include_tasks: verify/volume.yml

    - name: include command checks
      ansible.builtin.include_tasks: verify/cmds.yml

  always:

    - name: cleanup temp files
      ansible.builtin.file:
        state: absent
        path: "{{ _tmpdir.path }}"
      when: _tmpdir is not skipped
