---
- name: create

  hosts: localhost

  gather_facts: false

  roles:

    - nephelaiio.plugins
    - nephelaiio.kind

  pre_tasks:

    - name: manage docker kind network
      community.docker.docker_network:
        name: "kind"
        enable_ipv6: false
        ipam_config:
          - subnet: "{{ docker_net_addr }}"
            gateway: "{{ docker_net_addr | ipaddr(1) | ipaddr('address') }}"
            iprange: "{{ kind_net_addr }}"

  post_tasks:

    - name: deploy open-iscsi tools
      block:

        - name: list cluster nodes
          command: "{{ kind_bin }} get nodes --name {{ kind_cluster_name }}"
          register: kind_cluster_node_query

        - name: update cache for cluster nodes
          command: "docker exec {{ item }} apt-get update"
          loop: "{{ kind_cluster_node_query.stdout_lines }}"

        - name: install iscsi tools on cluster nodes
          command: "docker exec {{ item }} apt-get install --yes open-iscsi"
          loop: "{{ kind_cluster_node_query.stdout_lines }}"

      when: k8s_longhorn_deploy | bool
