---
- name: create strimzi namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    api_version: v1
    kind: Namespace
    name: strimzi-test
  register: strimzi_namespace_create
  retries: "{{ k8s_retry_num }}"
  delay: "{{ k8s_retry_delay }}"
  until: strimzi_namespace_create is success

- name: create test strimzi cluster
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    resource_definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      metadata:
        name: strimzi-test
        namespace: strimzi-test
      spec:
        kafka:
          replicas: 1
          listeners:
            - name: plain
              port: 9092
              type: internal
              tls: false
          storage:
            type: persistent-claim
            size: 1Gi
          config:
            offsets.topic.replication.factor: 1
            transaction.state.log.replication.factor: 1
            transaction.state.log.min.isr: 1
            default.replication.factor: 1
            min.insync.replicas: 1
        zookeeper:
          replicas: 1
          storage:
            type: persistent-claim
            size: 100Gi
        entityOperator:
          topicOperator: {}
          userOperator: {}
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 60
    wait_timeout: 600
  register: strimzi_cluster_create
  retries: "{{ k8s_retry_num }}"
  delay: "{{ k8s_retry_delay }}"
  until: strimzi_cluster_create is success

- name: create test strimzi topic
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    resource_definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        name: strimzi-test
        namespace: strimzi-test
        labels:
          strimzi.io/cluster: strimzi-test
      spec:
        partitions: 1
        replicas: 1
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 60
    wait_timeout: 120
  register: strimzi_topic_create
  retries: "{{ k8s_retry_num }}"
  delay: "{{ k8s_retry_delay }}"
  until: strimzi_topic_create is success
