---
- name: create

  hosts: localhost

  gather_facts: false

  roles:

    - nephelaiio.plugins
    - nephelaiio.kind

  pre_tasks:

    - name: manage docker kind network
      community.docker.docker_network:
        name: "kind"
        enable_ipv6: false
        ipam_config:
          - subnet: "{{ docker_net_addr }}"
            gateway: "{{ docker_net_addr | ipaddr(1) | ipaddr('address') }}"
            iprange: "{{ kind_net_addr }}"
