---
- name: destroy

  hosts: localhost

  gather_facts: false

  vars_files: ../vars/shared.yml

  tasks:

    - name: list kind clusters
      ansible.builtin.command: >-
        {{ _kind_bin }} get clusters -q
      register: kind_cluster_query
      changed_when: false

    - name: destroy kind cluster
      ansible.builtin.shell: >-
        {{ _kind_bin }} get clusters | grep molecule &&
        {{ _kind_bin }} delete cluster --name {{ _cluster_name }}
      when: _cluster_name in kind_cluster_query.stdout_lines
