---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: localhost
driver:
  name: delegated
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          ansible_connection: local
          ansible_python_interpreter: python

          docker_net_addr: 172.19.0.0/16

          kind_net_addr: 172.19.0.0/24
          kind_cluster_name: molecule-k8s
          kind_kubeconfig: "{{ k8s_kubeconfig }}"

          k8s_kubeconfig: ${MOLECULE_EPHEMERAL_DIRECTORY}/config
          k8s_helm_bin: ${MOLECULE_EPHEMERAL_DIRECTORY}/helm
          k8s_argocd_namespace: argocd
          k8s_argocd_exec_timeout: 3m
          k8s_address_pool_private_iprange: 172.19.1.0/24
          k8s_address_pool_ispa_iprange: 172.19.2.0/24
          k8s_address_pool_ispb_iprange: 172.19.3.0/24
          k8s_metallb_speaker_secret: secret
          k8s_certmanager_issuer: local
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - prepare
    - create
  check_sequence:
    - dependency
    - cleanup
    - prepare
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - prepare
    - create
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - prepare
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - prepare
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - converge
    - verify
    - side_effect
    - cleanup
    - destroy
