---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: localhost
driver:
  name: delegated
provisioner:
  name: ansible
  playbooks:
    prepare: ../common/prepare.yml
    create: ../common/create.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    hosts:
      all:
        vars:
          # test-only vardefs
          ansible_connection: local
          ansible_python_interpreter: python
          docker_net_addr: 172.19.0.0/16
          k8s_kubeconfig: ${MOLECULE_EPHEMERAL_DIRECTORY}/config
          k8s_helm_bin: ${MOLECULE_EPHEMERAL_DIRECTORY}/helm
          k8s_certmanager_issuer: local
          k8s_cluster_name: molecule.nephelai.io

          # kind vardefs
          kind_bin: ${MOLECULE_EPHEMERAL_DIRECTORY}/kind
          kind_net_addr: 172.19.0.0/24
          kind_cluster_name: molecule-k8s
          kind_kubeconfig: "{{ k8s_kubeconfig }}"

          # zalando vardefs
          zalando_user: molecule
          zalando_db: zalando
          zalando_team: test
          zalando_namespace: zalando-test

          # role vardefs
          k8s_address_pool_private_iprange: 172.19.1.0/24
          k8s_address_pool_public_iprange: 172.19.2.0/24
          k8s_metallb_speaker_secret: secret
          k8s_verifier_path: ${MOLECULE_EPHEMERAL_DIRECTORY}
          k8s_strimzi_deploy: false
          k8s_argocd_deploy: false
          k8s_longhorn_deploy: false
          k8s_awxoperator_deploy: false
          k8s_secrets:
            - namespace: secret-test
              name: molecule-secret
              data:
                username: "{{ 'molecule' | b64encode }}"
                password: "{{ 'molecule' | b64encode }}"
verifier:
  name: ansible
