---
- name: verify

  hosts: all

  gather_facts: false

  vars_files: ../vars/shared.yml

  roles:

    - nephelaiio.plugins

  tasks:

    - name: query helm deployments
      shell: >-
        {{ _helm_bin }} list -A -o json
      environment:
        KUBECONFIG: "{{ _kubeconfig }}"
      register: helm_query

    - name: record failed helm deployments
      set_fact:
        helm_failed: "{{ helm_errors | map('map_join', ['namespace', 'name', 'app_version'], '.') }}"
      vars:
        helm_deployments: "{{ helm_query.stdout | from_json }}"
        helm_errors: "{{ helm_deployments | rejectattr('status', 'equalto', 'deployed') }}"

    - name: fail helm deployment check
      fail:
        msg: "the following helm deployments failed [{{ helm_failed | join(', ') }}]"
      when: helm_failed | length > 0

    - name: include argocd checks
      include_tasks: verify/argocd.yml
