---
- name: verify

  hosts: all

  gather_facts: false

  roles:

    - nephelaiio.plugins

  tasks:

    - name: verify cluster
      include_role:
        name: nephelaiio.k8s
        tasks_from: verify
