---
- name: verify

  hosts: all

  gather_facts: false

  roles:

    - nephelaiio.plugins

  tasks:

    - name: print debug information
      ansible.builtin.debug:
        msg: "using kubeconfig at '{{ k8s_kubeconfig }}'"

    - name: include helm checks
      include_tasks: verify/helm.yml

    - name: include helm checks
      include_tasks: verify/pods.yml

    - name: include argocd checks
      ansible.builtin.include_tasks: verify/argocd.yml
