---
- name: manage cert-manager helm chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: "{{ k8s_certmanager_chart.name }}"
    chart_repo_url: "{{ k8s_certmanager_chart.repo }}"
    chart_version: "{{ k8s_certmanager_chart.release }}"
    release_namespace: "{{ k8s_certmanager_namespace }}"
    create_namespace: true
    state: present
    wait: true
    wait_timeout: "{{ k8s_certmanager_wait_timeout }}s"
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    binary_path: "{{ k8s_helm_bin | default(omit) }}"
    values:
      installCRDs: true
      podDnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8

- name: deploy cloudflare cluster issuer
  block:

    - name: create certmanager secret
      kubernetes.core.k8s:
        namespace: "{{ k8s_certmanager_namespace }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        state: present
        resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudflare-api-token-secret
            namespace: "{{ k8s_certmanager_namespace }}"
          type: Opaque
          data:
            api-token: "{{ k8s_certmanager_secret | b64encode }}"

    - name: create letsencrypt issuer
      kubernetes.core.k8s:
        namespace: "{{ k8s_certmanager_namespace }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        state: present
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: "{{ k8s_certmanager_issuer_name }}"
          spec:
            acme:
              server: "{{ k8s_certmanager_issuer_server | default('https://acme-staging-v02.api.letsencrypt.org/directory') }}"
              email: "{{ k8s_certmanager_acme_email }}"
              privateKeySecretRef:
                name: letsencrypt-production
              solvers:
                - dns01:
                    cloudflare:
                      email: "{{ k8s_certmanager_acme_email }}"
                      apiKeySecretRef:
                        name: cloudflare-api-token-secret
                        key: api-token

  when: k8s_certmanager_issuer != 'local'

- name: deploy local cluster issuer
  block:

    - name: create bootstrap issuer
      kubernetes.core.k8s:
        name: bootstrap-issuer
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        namespace: "{{ k8s_certmanager_namespace }}"
        state: present
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: bootstrap-issuer
          spec:
            selfSigned: {}

    - name: create ca certificate
      kubernetes.core.k8s:
        namespace: "{{ k8s_certmanager_namespace }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        state: present
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: cluster-ca
          spec:
            isCA: true
            commonName: cluster-issuer-ca
            secretName: cluster-issuer-secret
            privateKey:
              algorithm: ECDSA
              size: 256
            issuerRef:
              name: bootstrap-issuer
              kind: ClusterIssuer

    - name: create cluster issuer
      kubernetes.core.k8s:
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        state: present
        resource_definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: "{{ k8s_certmanager_issuer_name }}"
          spec:
            ca:
              secretName: cluster-issuer-secret

  when: k8s_certmanager_issuer == 'local'
