---
- name: check cluster type input
  ansible.builtin.fail:
    msg: "k8s_cluster_type must be one of [{{ valid_cluster_types | map('map_format', \"'%s'\") | join(', ') }}]"
  vars:
    valid_cluster_types:
      - local
      - aws
  when: k8s_cluster_type not in valid_cluster_types

- name: check local cluster settings
  block:

    - name: check private address pool range
      ansible.builtin.fail:
        msg: "private address pool range must be set"
      when: k8s_address_pool_private_iprange | length == 0

    - name: check public address pool name
      ansible.builtin.fail:
        msg: "public address pool name must be set"
      when: k8s_address_pool_public_name | length == 0

    - name: check public address pool range
      ansible.builtin.fail:
        msg: "public address pool range must be set as subnet/prefix"
      when: k8s_address_pool_public_iprange | length == 0 or not (k8s_address_pool_public_iprange | ansible.utils.ipaddr('network/prefix'))

  when: k8s_cluster_type == 'local'

- name: check metallb speaker secret is set
  ansible.builtin.fail:
    msg: "k8s_metallb_speaker_secret must be set"
  when: k8s_metallb_speaker_secret is not defined or k8s_metallb_speaker_secret | length == 0

- name: check nginx ingress controller release
  ansible.builtin.fail:
    msg: "k8s_nginx_chart_release must be at least '{{ chart_release_min }}'"
  vars:
    chart_release_min: '4.0.15'
  when: (k8s_nginx_chart_release | regex_replace('^v' ,'')) is version(chart_release_min | regex_replace('^v', ''), operator='lt')

- name: check certmanager release
  ansible.builtin.fail:
    msg: "k8s_certmanager_chart_release must be at least '{{ chart_release_min }}'"
  vars:
    chart_release_min: 'v1.6.1'
  when: (k8s_certmanager_chart_release | regex_replace('^v', '')) is version(chart_release_min | regex_replace('^v', '' ), operator='le')
