---
- name: deploy quay operator subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: quay-operator
        namespace: operators
      spec:
        channel: "{{ k8s_quay_channel }}"
        name: project-quay
        source: operatorhubio-catalog
        sourceNamespace: olm
        installPlanApproval: "{{ k8s_quay_approval }}"
