---
- name: deploy strimzi operator subscription
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    resource_definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: strimzi-operator
        namespace: operators
      spec:
        channel: "{{ k8s_strimzi_channel }}"
        name: strimzi-kafka-operator
        source: operatorhubio-catalog
        sourceNamespace: olm
